App_home:
  path: /
  defaults: { _controller: ConventionGeekEventBundle:Index:index}

App_about:
  path: /about
  defaults: { _controller: ConventionGeekMainBundle:Default:about}

App_irlEvent:
  path: /TGS2017
  defaults: { _controller: ConventionGeekMainBundle:Default:irlEvent}

CGEvent_conventions:
  path: /convention
  defaults: { _controller: ConventionGeekEventBundle:Convention:Conventions}

CGEvent_annuaire:
  path: /annuaire
  defaults: { _controller: ConventionGeekEventBundle:Annuaire:annuaire}

CGEvent_event:
  path: /convention/{eventid}
  defaults: { _controller: ConventionGeekEventBundle:Event:event}

sonata:
    resource: routing_sonata.yml

fos_user_delete_account:
  path: /profile/delete/
  defaults: { _controller: ApplicationSonataUserBundle:User:deleteUser }


