App_home:
  path: /
  defaults: { _controller: ConventionGeekEventBundle:Index:index}

App_about:
  path: /about
  defaults: { _controller: AppBundle:Default:about}

App_irlEvent:
  path: /TGS2017
  defaults: { _controller: AppBundle:Default:irlEvent}

sonata:
    resource: routing_sonata.yml



