# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    admin.convention:
            class: ConventionGeek\EventBundle\Admin\ConventionAdmin
            arguments: [~, ConventionGeek\EventBundle\Entity\Convention, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: CG - Conventions, label: Convention }
            public: true

    admin.date-event:
            class: ConventionGeek\EventBundle\Admin\DateEventAdmin
            arguments: [~, ConventionGeek\EventBundle\Entity\DateEvent, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: CG - Conventions, label: Dates événements }
            public: true

    admin.contact:
            class: ConventionGeek\ContactBundle\Admin\ContactAdmin
            arguments: [~, ConventionGeek\ContactBundle\Entity\Contact, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: CG - Contact, label: Contact }
            public: true



    admin.conventionform:
          class: ConventionGeek\ContactBundle\Admin\ConventionFormAdmin
          arguments: [~, ConventionGeek\ContactBundle\Entity\ConventionForm, ~]
          tags:
          - { name: sonata.admin, manager_type: orm, group: CG - Contact, label: Conventions Form  }
          public: true
