fos_rest:
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  format_listener:
    enabled: true
    rules:
    # you can specifically target the exception controller
    - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    # setting a priority to */* basically means any format will be matched
    - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }