<?php

namespace ConventionGeek\ContactBundle\Repository;

/**
 * ConventionFormRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConventionFormRepository extends \Doctrine\ORM\EntityRepository
{
}
