<?php

namespace ConventionGeek\EventBundle\Repository;

/**
 * DateEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDateForIndex()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.dateDebut BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime(date('Y').'-'.date('m').'-'.date('d')))
            ->setParameter('end',   new \Datetime(date('Y').'-'.(date('m')+2).'-'.date('d')))
            ->orderBy('a.dateDebut', 'ASC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAllDateAfterToday()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.dateDebut >= :start ')
            ->setParameter('start', new \Datetime(date('Y').'-'.date('m').'-'.date('d')))
            ->orderBy('a.dateDebut', 'ASC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
